feat: tag docker image with the release version published

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -43,9 +43,30 @@ jobs:
         with:
           images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
 
+      - name: Extract Tools versions from tag
+        id: extract_tools_versions
+        run: |
+          if [[ ! "${TAG_NAME}" =~ ^[0-9]+\.[0-9]+\.[0-9]+-apprise[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Error: Tag must follow 'X.Y.Z-appriseA.B.C' format."
+            exit 1
+          fi
+
+          # Extract Wazuh: Everything before "-apprise"
+          WAZUH_VERSION=$(echo $TAG_NAME | sed 's/-apprise.*//')
+
+          # Extract Apprise: Everything after "-apprise"
+          APPRISE_VERSION=$(echo $TAG_NAME | sed 's/.*-apprise//')
+
+          # Set outputs for use in later steps
+          echo "wazuh_version=$WAZUH_VERSION" >> $GITHUB_OUTPUT
+          echo "apprise_version=$APPRISE_VERSION" >> $GITHUB_OUTPUT
+        env:
+          TAG_NAME: ${{ github.event.release.tag_name }}
+
         # This step uses the `docker/build-push-action` action to build the image, based on your repository's `Dockerfile`. If the build succeeds, it pushes the image to GitHub Packages.
         # It uses the `context` parameter to define the build's context as the set of files located in the specified path. For more information, see [Usage](https://github.com/docker/build-push-action#usage) in the README of the `docker/build-push-action` repository.
         # It uses the `tags` and `labels` parameters to tag and label the image with the output from the "meta" step.
+        # It uses `build-args` for adding Tools version as labels (see `Dockerfile`)
       - name: Build and push Docker image
         id: push
         uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
@@ -55,6 +76,9 @@ jobs:
           push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
+          build-args: |
+            WAZUH_VERSION=${{ steps.extract_tools_versions.outputs.wazuh_version }}
+            APPRISE_VERSION=${{ steps.extract_tools_versions.outputs.apprise_version }}
 
         # This step generates an artifact attestation for the image, which is an unforgeable statement about where and how it was built. It increases supply chain security for people who consume the image. For more information, see [Using artifact attestations to establish provenance for builds](/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds).
       - name: Generate artifact attestation
